### ISSUE TITLE
Remove passive learning phase from school time

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/classroom-abm#11]
Following on from #10:

> On a school day we should have 5.5h of school learning which involves no passive learning; plus 5.5h of passive learning corresponding to out of school time On holidays we should have 11 hrs of passive learning.

The code should be modified so that the passive learning phase is not run during school time.

**Comment by alisonrclarke** [comment]
@PeterTymms I've just realised that with the current parameters, once this is implemented, students will be likely to learn more at home than in school. Both active and passive learning uses:

```
set end_maths end_maths + 1.2 * ((random-normal ((5 + ability) / 2000) .08) )
```
 but the active learning in school time only occurs if the student's status is green.

Should I update the parameters while I'm changing this?

**Comment by alisonrclarke** [comment]
I've now added variables for the home and school learning multipliers, which can be modified in BehaviorSpace. I have not added UI elements as I presume once the model is set up (and we update the initial values) you don't want the user to change these - is that right @PeterTymms ?

**Comment by PeterTymms** [comment]
Yes, that sounds right Sent from Mail for Windows 10 From: Alison ClarkeSent: 06 November 2020 08:09To: DurhamARC/classroom-abmCc: PeterTymms; MentionSubject: Re: [DurhamARC/classroom-abm] Remove passive learning phase from school time (#11) I've now added variables for the home and school learning multipliers, which can be modified in BehaviorSpace. I have not added UI elements as I presume once the model is set up (and we update the initial values) you don't want the user to change these - is that right @PeterTymms ?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
