### ISSUE TITLE
Replace graph with maths scores for selected pupils

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/classroom-abm#92]
Peter said:

> I’m not sure that we need to graph the numbers of learning and disruptive students.  Instead could we put in the Maths scores of selected pupils – say those who start highest, middle and lowest?

(Check with Peter that the scores inside the dots aren't sufficient.)

**Comment by PeterTymms** [comment]
I saw the dots but thought that graphing would be good as well Sent from Mail for Windows 10 From: Alison ClarkeSent: 09 August 2021 13:13To: DurhamARC/classroom-abmCc: SubscribedSubject: [DurhamARC/classroom-abm] Replace graph with maths scores for selected pupils (#92) Peter said:I’m not sure that we need to graph the numbers of learning and disruptive students. Instead could we put in the Maths scores of selected pupils – say those who start highest, middle and lowest?(Check with Peter that the scores inside the dots aren't sufficient.)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alisonrclarke** [comment]
Fixed by PR #116
